const R4_ANGLES=[90,270,180,0,90],R4_RAINBOW=["青O","赤M","紫S","黄T","藍R","橙E","緑E"];
function r4Count(){return [room4State.wall,room4State.box,room4State.star,room4State.lightPuzzle,room4State.meteors].filter(Boolean).length}
function r4All(){return r4Count()===5}
function r4Correct(){return r4All()&&room4State.angles.every((v,i)=>v===R4_ANGLES[i])}
function showFourthRoom(savedState){
 Dialogue.stop();firstRoomState=undefined;room2State=undefined;room3State=undefined;currentScene="room04";
 room4State={door:false,wall:false,box:false,star:false,lightPuzzle:false,meteors:false,angles:[0,0,0,0,0],rainbow:[...R4_RAINBOW],lightOn:false,completed:false,memorySeen:false,nextRoomTransitionSeen:false,hanaSleepSeen:false,highlightEnabled:true,...savedState};
 if(!Array.isArray(room4State.angles)||room4State.angles.length!==5)room4State.angles=[0,0,0,0,0];
 if(!Array.isArray(room4State.rainbow)||room4State.rainbow.length!==7)room4State.rainbow=[...R4_RAINBOW];
 game.innerHTML=`<main class="room room-four room4-arriving ${room4State.completed?"is-restored":""}" aria-label="第四の部屋"><header class="room-header"><p class="room-label">第四の部屋</p><p class="room-color-status">${room4State.completed?"記憶を取り戻した部屋":"天文展示室"}</p></header><div class="room-stage-wrap"><section class="room-stage room4-stage"><div class="r4-sky" aria-hidden="true"></div><div class="r4-door-art"></div><div class="r4-light-art"></div><div class="r4-display-art"></div><div id="r4Projection" class="r4-projection"></div><button class="object r4obj r4door" id="r4Door"><span>扉</span></button><button class="object r4obj r4light" id="r4Light"><span>ライト</span></button><button class="object r4obj r4stand" id="r4Stand"><span>パネル台</span></button><button class="object r4obj r4const" id="r4Const"><span>星座一覧</span></button><button class="object r4obj r4meteor" id="r4Meteor"><span>流れ星</span></button><button class="object r4obj r4p1" id="r4P1"><span>謎1</span></button><button class="object r4obj r4p2" id="r4P2"><span>謎2</span></button><button class="object r4obj r4p3" id="r4P3"><span>謎3</span></button><button class="object r4obj r4wall" id="r4Wall" ${room4State.wall?"disabled":""}><span>壁の透明板</span></button><button class="object r4obj r4box" id="r4Box"><span>質問箱</span></button><button class="object r4obj r4hana" id="r4Hana"><span>ハナ</span></button></section></div><nav class="room-navigation"><span></span><p id="r4Count">ガラスパネル ${r4Count()} / 5</p><span></span></nav><p class="explore-status" id="exploreStatus">気になる場所をクリックしてください。</p></main>`;
 [["r4Door",r4Door],["r4Light",r4Light],["r4Stand",r4Stand],["r4Const",r4Const],["r4Meteor",r4Meteor],["r4P1",r4P1],["r4P2",r4P2],["r4P3",r4P3],["r4Wall",r4Wall],["r4Box",r4Box],["r4Hana",r4Hana]].forEach(([id,fn])=>document.getElementById(id).addEventListener("click",fn));
 r4Projection();
 if(savedState){showRoomNotice("続きから再開しました。","r4resume","narration");if(room4State.nextRoomTransitionSeen)setTimeout(r4NextPlaceholder,150);else if(room4State.completed&&!room4State.memorySeen)setTimeout(r4Memory,150)}else showRoomDialog(room4IntroLines);
 if(window.GameplayUI)GameplayUI.installRoom({sceneId:"room04",title:"第四の部屋",objective:()=>room4State.completed?"次の部屋へ進む":r4All()?"5枚のパネルの向きを合わせる":"5枚のガラスパネルを集める",onCompanion:r4Hana,getHighlights:()=>!!room4State.highlightEnabled,setHighlights:v=>{room4State.highlightEnabled=!!v;saveGame()}});
 saveGame();
}
function r4Door(){
 if(room4State.completed&&room4State.memorySeen){showRoomDialog([{logId:"r4open1",logType:"investigation",speaker:"ト書き",text:"扉の鍵は開いている。"},{logId:"r4open2",logType:"narration",speaker:"主人公",thought:true,text:"先へ行けば、名前のことも思い出せるかもしれない。"}],r4Exit);return}
 if(room4State.door){showRoomDialog([{logId:"r4drepeat",logType:"narration",speaker:"システム",text:"『散らばる星を重ね、夜空にひとつの姿を描け。』"}]);return}
 showRoomDialog(room4DoorLines,()=>{room4State.door=true;saveGame()});
}
function r4Light(){
 room4State.lightOn=true;saveGame();r4Projection();
 if(r4Count()===0){showRoomDialog([{logId:"r4le1",logType:"investigation",speaker:"ト書き",text:"スイッチを入れる。ライトが点灯し、左の壁を照らした。ただ、壁が明るく照らされただけだ。"},{logId:"r4le2",logType:"dialogue",speaker:"主人公",text:"これだけじゃ、何も起きないみたいだな"}]);return}
 if(!r4All()){showRoomNotice("集めたパネルを通して星が映ったが、まだパネルが足りない。","r4partial");return}
 if(!r4Correct()){showRoomDialog([{logId:"r4lw1",logType:"investigation",speaker:"ト書き",text:"ライトの光がパネルを通り、左の壁にいくつもの星が映し出される。"},{logId:"r4lw2",logType:"dialogue",speaker:"主人公",text:"……星は映ったけど。これじゃ、まだ何の形か分からないな"},{logId:"r4lw3",logType:"dialogue",speaker:"主人公",text:"パネルの向きが違うのかもしれない"}]);return}
 r4Complete();
}
function r4Projection(){const p=document.getElementById("r4Projection");if(!p)return;p.className="r4-projection"+(room4State.lightOn?" on":"")+(room4State.completed?" complete":"");p.innerHTML=room4State.lightOn?Array.from({length:r4Count()*3},(_,i)=>`<i style="--x:${10+(i*31)%78}%;--y:${12+(i*43)%72}%"></i>`).join(""):""}
function r4Stand(){
 if(!r4All()){showRoomDialog([{logId:"r4s1",logType:"investigation",speaker:"ト書き",text:"ライトの前に、透明な板を差し込めそうな枠が並んでいる。数えてみると、全部で五つある。"},{logId:"r4s2",logType:"dialogue",speaker:"主人公",text:"……五枚分ってことか"},{logId:"r4s3",logType:"investigation",speaker:"ト書き",text:`今は、${r4Count()}枚のガラスパネルを持っている。`}]);return}
 const o=document.createElement("div");o.className="device-overlay r4-panel-overlay";o.innerHTML=`<section class="r4-panel-ui"><button class="device-close">×</button><h2>ガラスパネル</h2><p>5枚を90度ずつ回転させ、星の位置を合わせる。</p><div class="r4-panels"></div><p class="r4-feedback"></p><button class="r4-shine">ライトを当てる</button></section>`;game.appendChild(o);
 const grid=o.querySelector(".r4-panels"),fb=o.querySelector(".r4-feedback"),close=activateDeviceModal(o,"r4Stand",o.querySelector(".device-close"));
 const draw=()=>{grid.innerHTML=room4State.angles.map((a,i)=>`<article><h3>パネル ${i+1}</h3><div class="r4-glass" style="transform:rotate(${a}deg)"><i></i><i></i><i></i></div><p>${a}°</p><button data-i="${i}">90°回転</button></article>`).join("");grid.querySelectorAll("[data-i]").forEach(b=>b.onclick=()=>{let i=+b.dataset.i;room4State.angles[i]=(room4State.angles[i]+90)%360;saveGame();draw()})};draw();
 o.querySelector(".r4-shine").onclick=()=>{room4State.lightOn=true;saveGame();if(r4Correct()){close();r4Complete()}else fb.textContent="星は映ったが、まだ何の形か分からない。向きを見直そう。"};
}
function r4Const(){showRoomDialog([{logId:"r4c1",logType:"investigation",speaker:"ト書き",text:"いくつかの星座と、その形が描かれたパネルが並んでいる。星の位置と名前を確認できる。おとめ座の図もある。"},{logId:"r4_final_zodiac_flowers",logType:"investigation",speaker:"ト書き",text:"隣には、12星座それぞれにまつわる花を紹介する展示も並んでいる。"},{logId:"r4c2",logType:"dialogue",speaker:"主人公",text:"これを見れば、星の形から星座を調べられそうだ"}])}
function r4Meteor(){showRoomDialog([{logId:"r4m1",logType:"investigation",speaker:"ト書き",text:"流れ星についての展示だ。流れ星は、宇宙空間の小さなちりや岩石が大気に飛び込み、高温になって光って見える現象らしい。地球が彗星の残したちりの中を通ると、流星群が見られることもある。"},{logId:"r4m2",logType:"dialogue",speaker:"主人公",text:"こんな小さいものが、あんなに明るく見えるんだな"}])}
function r4WordPuzzle(kind){
 const solved=kind==="STAR"?room4State.star:room4State.lightPuzzle;if(solved){showRoomNotice("この謎は解き終えている。","r4done"+kind);return}
 const o=document.createElement("div");o.className="device-overlay r4-mini-overlay";
 const body=kind==="STAR"?`<div class="r4-digits"><b class="silver">1</b><b class="white">4</b><b class="black">3</b><b class="green">2</b></div>`:`<div class="r4-flags"><span>⬜⬜⬜<br>🟥🟥🟥　<b>3</b></span><span>🟥<br>🟨🟨🟨<br>🟥　<b>4</b></span><span>⬛⬛｜🟨🟨🟨｜🟥🟥　<b>4</b></span><span>🟥<br>⬜<br>🟦🟦🟦🟦<br>⬜<br>🟥　<b>2</b></span><span>🟩🟩｜⬜｜🟥🟥　<b>2</b></span></div><p class="r4-moon">月の模様の展示：国旗と英語国名 POLAND / SPAIN / BELGIUM / THAILAND / ITALY など。見え方には地域・時代・伝承によって諸説があります。</p>`;
 o.innerHTML=`<section class="r4-mini"><button class="device-close">×</button><h2>謎 ${kind==="STAR"?"1":"2"}</h2>${body}<label>答え<input autocomplete="off"></label><button class="r4-answer">答える</button><p class="r4-feedback"></p></section>`;game.appendChild(o);const input=o.querySelector("input"),fb=o.querySelector(".r4-feedback"),close=activateDeviceModal(o,kind==="STAR"?"r4P1":"r4P2",input);
 o.querySelector(".r4-answer").onclick=()=>{if(input.value.trim().toUpperCase()!==kind){fb.textContent=kind==="STAR"?"色の英語名と数字を使えそうだ。":"色の並びを国旗として見て、英語国名から数字の位置を読もう。";return}if(kind==="STAR")room4State.star=true;else room4State.lightPuzzle=true;saveGame();close();showRoomDialog([{logId:"r4"+kind+"ok1",logType:"dialogue",speaker:"主人公",text:`${kind}……${kind==="STAR"?"星":"光"}、か`},{logId:"r4"+kind+"ok2",logType:"investigation",speaker:"ト書き",text:"カチッ――展示ケースのロックが外れた。中から透明なパネルを取り出す。"},{logId:"r4"+kind+"ok3",logType:"narration",speaker:"システム",text:"【ガラスパネルを入手】"}],r4Refresh)};
}
function r4P1(){r4WordPuzzle("STAR")} function r4P2(){r4WordPuzzle("LIGHT")}
function r4P3(){
 if(room4State.meteors){showRoomNotice("謎3は解き終えている。","r4p3done");return}
 const o=document.createElement("div");o.className="device-overlay r4-mini-overlay";o.innerHTML=`<section class="r4-mini"><button class="device-close">×</button><h2>謎3</h2><p>七色のプレートを正しい順番に並べる。</p><div class="r4-rainbow"></div></section>`;game.appendChild(o);const list=o.querySelector(".r4-rainbow"),close=activateDeviceModal(o,"r4P3",o.querySelector(".device-close"));
 const draw=()=>{list.innerHTML=room4State.rainbow.map((v,i)=>`<div class="c${v.slice(-1)}"><b>${v}</b><button data-i="${i}" data-d="-1" ${i===0?"disabled":""}>↑</button><button data-i="${i}" data-d="1" ${i===6?"disabled":""}>↓</button></div>`).join("");list.querySelectorAll("[data-i]").forEach(b=>b.onclick=()=>{let i=+b.dataset.i,j=i+(+b.dataset.d);[room4State.rainbow[i],room4State.rainbow[j]]=[room4State.rainbow[j],room4State.rainbow[i]];saveGame();if(room4State.rainbow.map(v=>v.slice(-1)).join("")==="METEORS"){room4State.meteors=true;saveGame();close();showRoomDialog([{logId:"r4p3ok1",logType:"dialogue",speaker:"主人公",text:"METEORS……流れ星、か"},{logId:"r4p3ok2",logType:"investigation",speaker:"ト書き",text:"カチッ――展示ケースの中から透明なパネルを取り出す。"},{logId:"r4p3ok3",logType:"narration",speaker:"システム",text:"【ガラスパネルを入手】"}],r4Refresh)}else draw()})};draw();
}
function r4Wall(){if(room4State.wall)return;showRoomDialog([{logId:"r4w1",logType:"dialogue",speaker:"主人公",text:"あれ……これって。もしかして、これもパネルなんじゃ……"},{logId:"r4w2",logType:"investigation",speaker:"ト書き",text:"壁に貼られている透明な板の端に指をかけると、外れた。"},{logId:"r4w3",logType:"narration",speaker:"システム",text:"【ガラスパネルを入手】"}],()=>{room4State.wall=true;saveGame();r4Refresh()})}
function r4Box(){if(room4State.box){showRoomNotice("質問箱の透明パネルは取り外してある。","r4boxdone");return}showRoomDialog([{logId:"r4b1",logType:"investigation",speaker:"ト書き",text:"質問箱を調べる。何気なく眺めていると、一面だけ材質が違う。"},{logId:"r4b2",logType:"dialogue",speaker:"主人公",text:"……あれ？ この部分、さっきのパネルと同じじゃないか？"},{logId:"r4b3",logType:"investigation",speaker:"ト書き",text:"端に手をかけると外せそうだ。箱から透明なパネルを取り外した。"},{logId:"r4b4",logType:"narration",speaker:"システム",text:"【ガラスパネルを入手】"}],()=>{room4State.box=true;saveGame();r4Refresh()})}
function r4Refresh(){const n=document.getElementById("r4Count");if(n)n.textContent=`ガラスパネル ${r4Count()} / 5`;const w=document.getElementById("r4Wall");if(w&&room4State.wall)w.disabled=true;showRoomNotice(r4All()?"5枚のガラスパネルが揃った。ライト前の台を調べよう。":`ガラスパネルを入手した。現在 ${r4Count()} / 5 枚。`,"r4cnt"+r4Count())}
function r4Hana(){
 if(!room4State.hanaSleepSeen){showRoomDialog([{logId:"r4h1",logType:"dialogue",speaker:"ハナ",text:"ふぁ……"},{logId:"r4h2",logType:"dialogue",speaker:"主人公",text:"眠いんですか？"},{logId:"r4h3",logType:"dialogue",speaker:"ハナ",text:"んー……ちょっと眠いかも"},{logId:"r4h4",logType:"dialogue",speaker:"ハナ",text:"大丈夫。謎、解こっか"}],()=>{room4State.hanaSleepSeen=true;saveGame()});return}
 const text=!room4State.door?"まずは扉を見てみたら？ 今回の謎が書いてあるかも":!r4All()?"透明なパネルは五枚必要みたい。展示だけじゃなくて、部屋そのものもよく見てみよう":"五枚は揃ったね。重ねる順番より、それぞれの向きを見た方がよさそうだよ";showRoomDialog([{logId:"r4hint"+r4Count(),logType:"dialogue",speaker:"ハナ",text}]);
}
function r4Complete(){
 if(room4State.completed)return;room4State.completed=true;room4State.lightOn=true;saveGame();r4Projection();game.querySelector(".room-four")?.classList.add("is-restored");const status=game.querySelector(".room-four .room-color-status");if(status)status.textContent="記憶を取り戻した部屋";
 showRoomDialog([{logId:"r4ok1",logType:"investigation",speaker:"ト書き",text:"ライトの光が、五枚のパネルを通り抜ける。左の壁に、いくつもの星が映し出された。今までばらばらだった星が、ひとつの形を描いている。"},{logId:"r4ok2",logType:"dialogue",speaker:"主人公",text:"これ……星座だ"},{logId:"r4ok3",logType:"narration",speaker:"ト書き",text:"右の壁にある星座一覧へ目を向ける。"},{logId:"r4_final_zodiac_flowers_complete",logType:"narration",speaker:"ト書き",text:"星座一覧の隣には、12星座それぞれにまつわる花を紹介する展示が並んでいる。"},{logId:"r4ok4",logType:"dialogue",speaker:"主人公",text:"……おとめ座"},{logId:"r4ok5",logType:"narration",speaker:"ト書き",text:"もう一度、壁を見る。その瞬間――おとめ座を形作る星のひとつが、強く輝き始めた。光は次第に強くなり、辺りを白く染めていく。"},{logId:"r4ok6",logType:"dialogue",speaker:"ハナ",text:"……スピカ"},{logId:"r4ok7",logType:"dialogue",speaker:"主人公",text:"え？"},{logId:"r4ok8",logType:"narration",speaker:"ト書き",text:"ハナの方を振り返ろうとした瞬間、視界がまばゆい光に包まれた。"}],r4Memory);
}
function r4Memory(){if(room4State.memorySeen)return;showRoomDialog([...room4FlashbackLines,...room4AfterMemoryLines],()=>{room4State.memorySeen=true;saveGame();r4Exit()})}
function r4Exit(){
 if(game.querySelector(".device-overlay,.room-dialog-overlay"))return;const o=document.createElement("div");o.className="device-overlay";o.innerHTML=`<section class="menu-panel room-exit-menu"><button class="device-close">×</button><h2>扉の先へ</h2><button id="r4Next">次の部屋へ向かう</button><button id="r4Stay">もう少し部屋を調べる</button></section>`;game.appendChild(o);const close=activateDeviceModal(o,"r4Door",o.querySelector("#r4Next"));o.querySelector("#r4Stay").onclick=close;o.querySelector("#r4Next").onclick=()=>{close();showRoomDialog([{logId:"r4x1",logType:"narration",speaker:"ト書き",text:"ドアノブに手をかける。"},{logId:"r4x2",logType:"narration",speaker:"ト書き",text:"扉が開くのを待つことすら、もどかしく感じる。"},{logId:"r4x3",logType:"narration",speaker:"ト書き",text:"扉の向こうへ足を踏み出す。背後から、ハナがついてくる気配がした。"},{logId:"r4x4",logType:"narration",speaker:"ト書き",text:"振り返ることなく、そのまま先へ進んだ。"},{logId:"r4x5",logType:"narration",speaker:"ト書き",text:"視界が、まばゆい光に包まれていく。"}],()=>{room4State.nextRoomTransitionSeen=true;saveGame();r4NextPlaceholder()})};
}
function r4NextPlaceholder(){showFifthRoom(roomStates.room05)}
function showFourthRoomBoundary(){if(room3State){room3State.nextRoomTransitionSeen=true;saveGame()}Dialogue.stop();game.innerHTML=`<div class="room-transition room4-transition"><img src="images/background/room01/room01_door_halfopen.png" alt="次の部屋へ"></div>`;setTimeout(()=>{if(game.querySelector(".room4-transition"))showFourthRoom(roomStates.room04)},1100)}

