// Run with Playwright installed. Set PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH for a custom Chromium.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{once}=require('node:events');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://local').pathname);const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return}fs.readFile(file,(error,data)=>{if(error){res.writeHead(404);res.end();return}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.mp3':'audio/mpeg','.wav':'audio/wav'})[path.extname(file)]||'application/octet-stream');res.end(data)})});server.listen(0,'127.0.0.1');
async function screenshot(page,name){if(!process.env.UI_SCREENSHOT_DIR)return;fs.mkdirSync(process.env.UI_SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.UI_SCREENSHOT_DIR,name)})}
(async()=>{await once(server,'listening');const b=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-dev-shm-usage'],headless:true});const page=await b.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);await page.locator('#settingsButton').click();assert.equal(await page.locator('.design-settings input[type=range]').count(),3);await page.keyboard.press('Escape');await page.evaluate(()=>{localStorage.setItem('saigononazo-help-seen','1');settings.instantText=true;showFirstRoom({hanaIntroduced:true,questionSeen:true,doorInspected:true})});await page.waitForTimeout(100);
const finish=async()=>{await page.evaluate(()=>{for(let i=0;i<1000&&document.querySelector('#roomNextButton');i++)Dialogue.advance()});await page.waitForTimeout(80)};
await page.evaluate(()=>showRoomDialog([{logId:'qa-hana',logType:'dialogue',speaker:'ハナ',text:'ここから一緒に最後の謎を解いていこう。'},{logId:'qa-player',speaker:'主人公',text:'手がかりを確認しよう。'}]));await page.waitForTimeout(80);assert.equal(await page.locator('.message-speaker').textContent(),'ハナ');assert.equal(await page.locator('.hana-portrait').isVisible(),true);await screenshot(page,'dialogue.png');
await page.getByRole('button',{name:'非表示',exact:true}).click();assert(await page.locator('.room-dialog').evaluate(el=>el.classList.contains('dialog-hidden')));await page.locator('.dialogue-restore').click({position:{x:1000,y:600}});assert.equal(await page.locator('.message').textContent(),'ここから一緒に最後の謎を解いていこう。');await page.keyboard.press('Enter');assert.equal(await page.locator('.message-speaker').count(),0);assert.equal(await page.locator('.message.player').textContent(),'手がかりを確認しよう。');await finish();
await page.getByRole('button',{name:'記録',exact:true}).first().click();assert((await page.locator('.design-record').count())>=1);await page.locator('.design-record').filter({hasText:'ここから一緒'}).click();await page.waitForTimeout(100);assert((await page.locator('.design-page').textContent()).includes('手がかり'));await page.keyboard.press('Escape');
await page.getByRole('button',{name:'設定',exact:true}).click();await page.getByRole('button',{name:'セーブ',exact:true}).click();assert.equal(await page.locator('.save-slot-card').count(),3);await page.locator('.save-slot-action').first().click();assert(await page.evaluate(()=>!!localStorage.getItem('saigononazo-save-v1-slot-1')));await page.keyboard.press('Escape');
await page.evaluate(()=>showSecondRoom({deskInspected:true,sheetFound:true}));await finish();await page.locator('#r2Blocks').click();await page.waitForTimeout(80);const tokens=page.locator('.room2-palette-token');console.log('PALETTE',await tokens.allTextContents());for(const i of [0,1,2,3,4])await tokens.nth(i).click();assert.equal(await page.evaluate(()=>room2State.guess.length),5);await screenshot(page,'puzzle-pc.png');await page.locator('.room2-submit').click();assert.equal(await page.evaluate(()=>room2State.guess.length),0);assert.equal(await page.evaluate(()=>room2State.history.length),1);await page.keyboard.press('Escape');await finish();
await page.setViewportSize({width:852,height:393});await page.evaluate(()=>showSecondRoomPuzzle());await page.waitForTimeout(100);await screenshot(page,'puzzle-mobile.png');const bounds=await page.locator('.room2-puzzle').boundingBox();assert(bounds.x>=0&&bounds.y>=0&&bounds.x+bounds.width<=852&&bounds.y+bounds.height<=393);await page.keyboard.press('Escape');await finish();
for(const [fn,n] of [['showThirdRoom',3],['showFourthRoom',4],['showFifthRoom',5],['showSixthRoom',6],['showSeventhRoom',7],['showEighthRoom',8]]){await page.evaluate(({fn})=>window[fn]({}),{fn});await finish();await page.waitForTimeout(150);console.log('ROOM',n,'HUD',await page.locator('.gameplay-hud-actions button').allTextContents());assert.equal(await page.locator('.gameplay-hud-actions button').count(),4);await screenshot(page,`room${n}-mobile.png`)}

await page.setViewportSize({width:1440,height:900});await page.evaluate(()=>{showFirstRoom({hanaIntroduced:true,questionSeen:true,doorInspected:true});settings.instantText=false;settings.textSpeed=100;showRoomDialog([{logId:'pause-typing',speaker:'ハナ',text:'文字送りの途中で記録を開いても、その位置を保ったまま戻れることを確認します。'}])});await page.waitForTimeout(200);await page.locator('.design-controls').getByRole('button',{name:'記録'}).click();const frozen=await page.locator('.message').textContent();await page.waitForTimeout(550);assert.equal(await page.locator('.message').textContent(),frozen);await page.keyboard.press('Escape');await page.waitForTimeout(200);assert((await page.locator('.message').textContent()).length>frozen.length);
await page.evaluate(()=>{settings.instantText=true;showFifthRoom({collected:['fish'],boardIntroSeen:true})});await finish();await page.getByRole('button',{name:'持ち物',exact:true}).click();await page.getByRole('button',{name:'魚のパネル',exact:true}).click();await page.getByRole('button',{name:'使う',exact:true}).click();assert.equal(await page.locator('.design-use-prompt').count(),1);await page.getByRole('button',{name:'キャンセル',exact:true}).click();assert.equal(await page.locator('.design-use-prompt').count(),0);await page.getByRole('button',{name:'持ち物',exact:true}).click();await page.getByRole('button',{name:'魚のパネル',exact:true}).click();await page.getByRole('button',{name:'使う',exact:true}).click();await page.locator('#r5Board').click();await page.waitForTimeout(100);assert(await page.locator('[data-tile="fish"]').evaluate(el=>el.classList.contains('selected')));await page.keyboard.press('Escape');
const phone=await b.newPage({viewport:{width:393,height:852},isMobile:true,hasTouch:true});phone.on('pageerror',e=>errors.push(e.message));await phone.goto(`http://127.0.0.1:${server.address().port}`);await phone.evaluate(()=>{localStorage.setItem('saigononazo-help-seen','1');settings.textSpeed=100;showFirstRoom({hanaIntroduced:true});showRoomDialog([{logId:'portrait-pause',speaker:'ハナ',text:'横向きになるまで会話の文字送りを止めます。'}])});await phone.waitForTimeout(200);assert(await phone.locator('.design-orientation').isVisible());const paused=await phone.locator('.message').textContent();await phone.waitForTimeout(400);assert.equal(await phone.locator('.message').textContent(),paused);await phone.setViewportSize({width:852,height:393});await phone.waitForTimeout(400);assert((await phone.locator('.message').textContent()).length>paused.length);await phone.close();

// Regression checks for the accumulated dialogue and investigation fixes.
await page.evaluate(()=>{currentScene='opening';settings.instantText=true;showOpening(0)});await page.waitForTimeout(100);
assert.equal(await page.locator('.room-dialog .design-controls').count(),1);
assert.equal(await page.locator('.gameplay-hud-actions button').count(),4);
const openingPanel=await page.locator('.room-dialog').boundingBox();
await page.evaluate(()=>Dialogue.advance());assert.equal(await page.evaluate(()=>openingIndex),1);
await page.evaluate(()=>Dialogue.advance());assert.equal(await page.evaluate(()=>openingIndex),2);
async function helpText(){await page.evaluate(()=>DesignUI.help());await page.waitForTimeout(80);let text='';for(let i=0;i<30;i++){text+=await page.locator('.design-page').textContent();const next=page.getByRole('button',{name:'次のページ',exact:true});if(await next.isDisabled())break;await next.click()}await page.keyboard.press('Escape');return text}
assert(!(await helpText()).includes('いろしる'));
await page.evaluate(()=>{showFirstRoom({hanaIntroduced:false,questionSeen:true,doorInspected:true});showRoomDialog(firstRoomScenario.hanaFirst.slice(3,6))});await page.waitForTimeout(100);
assert.equal(await page.locator('.message-speaker').textContent(),'？？？');
const roomPanel=await page.locator('.room-dialog').boundingBox();assert(Math.abs(roomPanel.x-openingPanel.x)<1&&Math.abs(roomPanel.height-openingPanel.height)<1);
await page.evaluate(()=>{for(let i=0;i<10&&document.querySelector('.message-speaker');i++)Dialogue.advance()});assert.equal(await page.locator('.message-speaker').count(),0);assert(await page.evaluate(()=>firstRoomState.hanaNameKnown));
await page.evaluate(()=>Dialogue.advance());assert.equal(await page.locator('.message-speaker').textContent(),'ハナ');await finish();
assert(!(await helpText()).includes('いろしる'));
await page.evaluate(()=>showFirstRoom({hanaIntroduced:true,questionSeen:true,doorInspected:true}));await finish();await page.locator('#hanaButton').click();await page.waitForTimeout(100);assert(await page.locator('#hanaButton').evaluate(el=>el.classList.contains('is-investigated')));await page.keyboard.press('Escape');
await page.evaluate(()=>{firstRoomState.posterInspected=true;saveGame()});await page.waitForTimeout(100);assert(!(await page.locator('#hanaButton').evaluate(el=>el.classList.contains('is-investigated'))));
await page.locator('#hanaButton').hover();const label=await page.locator('#hanaButton > span').boundingBox();assert(label.height<30&&label.width<100);
await page.evaluate(()=>{settings.instantText=false;settings.textSpeed=100;showRoomDialog([{logId:'fixed-player',speaker:'主人公',text:'文字が増えても、この位置から右へ表示します。'}])});await page.waitForTimeout(200);const before=await page.locator('.message.player').boundingBox();await page.waitForTimeout(300);const after=await page.locator('.message.player').boundingBox();assert(Math.abs(before.x-after.x)<1);assert(before.x<roomPanel.x+roomPanel.width*.5);await page.evaluate(()=>Dialogue.advance());assert(Math.abs((await page.locator('.message.player').boundingBox()).x-before.x)<1);await screenshot(page,'player-fixed.png');
await page.evaluate(()=>{settings.instantText=true;showSecondRoom({deskInspected:true,sheetFound:true})});await finish();assert((await helpText()).includes('いろしる'));
console.log('ERRORS',errors);assert.deepEqual(errors,[]);await b.close();server.close();console.log('PASS UI: layout, dialogue, hidden restore, history pause, slots, puzzle input, rooms 1–8')})().catch(e=>{console.error(e);server.close();process.exit(1)})
